# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 清华大学 TUNA 镜像源
brand: TUNA mirrors
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

gems:
    - jekyll-babel

exclude: [Gemfile, Gemfile.lock, README.md]

# Content Related
new_mirrors: [openwrt, mongodb, anaconda, packman, gnu, osmc]

issue: 由于机房电力系统维护，我们暂时关闭镜像服务器。由此带来不便，我们十分抱歉。
backtime: 2016-03-13 12:00
